# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'Google-Maps_ARKit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Google-Maps_ARKit
  pod 'PusherSwift', '~> 5.0.1'

  target 'Google-Maps_ARKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Google-Maps_ARKitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
