# Uncomment the next line to define a global platform for your project
platform :ios, '11.2'

target 'arkit-demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for arkit-demo
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'PusherSwift'

  target 'arkit-demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'arkit-demoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
